🐛 Add PowerShell Core check to pre-commit hook
The pre-commit hook has been updated to check whether PowerShell Core 7.4.1 or later is installed and available in PATH. If PowerShell Core is not found, it will display an error message and suggest installing the missing dependency or proceeding with the --no-verify flag to skip the pre-commit hooks.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,4 +1,12 @@
 #!/bin/sh
 echo 
+
+if ! which pwsh >/dev/null; then
+    echo "pwsh not found in PATH"
+    echo "Please install PowerShell Core 7.4.1 or later and try again or append --no-verify to your git command to skip pre-commit hooks"
+    exit 1
+fi
+
 exec pwsh -NonInteractive -NoProfile -File './.githooks/pre-commit-hook.ps1'
 exit
+
